### ISSUE TITLE
(in-)compatibility with calender

### ISSUE THREAD

**Issue by fwolfst** [dhmgroup/bulma-extensions-rails#1]
Thanks, works great.
I run into issues when having the stylesheet included in parallel with the (now separate) Calendar plugin (https://creativebulma.net/product/calendar/demo).

I believe that the included stylesheets cover part of the calender (which was included in bulma extension in the past if I am not mistaken), but lack the javascript needed.

If you point out the exact source from where you pulled the css file one could do some digging easier; and this would be a nice extension to the README, too. Where btw, you could mention that the original css itself was released under the MIT.

Documenting the later part would also make it easy for contributors to work on new releases once the bulma-extensions get updated.

**Comment by theeomm** [comment]
I haven't worked with rails in a while now. However, I updated the package to match the latest version of the package. However, I would appreciate if you could confirm that everything is working fine now.
